name: Branch Release

on:
  push

jobs:
  branch_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest' # Specify the Bun version you want to use

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Set Version from Branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SHORT_SHA=$(git rev-parse --short HEAD)
          BASE_VERSION="0.1.0" # Define a base version
          VERSION="${BASE_VERSION}-${BRANCH_NAME}-${SHORT_SHA}"
          npm version $VERSION --no-git-tag-version

      - name: Configure NPM Authentication
        run: |
          echo "@bitte-ai:registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish with npm
        if: ${{ github.ref_name != 'main'}}
        run: npm publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}